
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // E/I Dimension
  { id: 1, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 2, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 3, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 4, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 5, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 6, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 7, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 8, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 9, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 10, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 11, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 12, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 13, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 80, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 84, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  
  // S/N Dimension
  { id: 14, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 15, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 16, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 17, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 18, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 19, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 20, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 21, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 22, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 23, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 24, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 25, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 26, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 27, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 81, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 85, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 93, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  
  // T/F Dimension
  { id: 28, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 29, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 30, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 31, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 32, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 33, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 34, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 35, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 36, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 37, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 38, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 39, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 40, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 41, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 82, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 86, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 92, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  
  // J/P Dimension
  { id: 42, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 43, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 44, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 45, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 46, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 47, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 48, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 49, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 50, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 51, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 52, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 53, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 54, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 55, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 83, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 87, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 91, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },

  // Additional mixed questions to reach 93 total
  { id: 56, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 57, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 58, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 59, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 60, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 61, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 62, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 63, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 64, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 65, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 66, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 67, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 68, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 69, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 70, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 71, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 72, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 73, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 74, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 75, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 76, dimension: 'E/I', optionA: { pole: 'E' }, optionB: { pole: 'I' } },
  { id: 77, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 78, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 79, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
  { id: 88, dimension: 'S/N', optionA: { pole: 'S' }, optionB: { pole: 'N' } },
  { id: 89, dimension: 'T/F', optionA: { pole: 'T' }, optionB: { pole: 'F' } },
  { id: 90, dimension: 'J/P', optionA: { pole: 'J' }, optionB: { pole: 'P' } },
];
